addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/UMFPACK/MATLAB
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/CHOLMOD/MATLAB
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/AMD/MATLAB
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/COLAMD/MATLAB
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/CCOLAMD/MATLAB
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/CAMD/MATLAB
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/ssget
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/CXSparse/MATLAB/Demo
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/CXSparse/MATLAB/CSparse
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/LDL/MATLAB
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/BTF/MATLAB
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/KLU/MATLAB
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/SPQR/MATLAB
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/RBio/RBio
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/MATLAB_Tools
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/MATLAB_Tools/Factorize
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/MATLAB_Tools/MESHND
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/MATLAB_Tools/LINFACTOR
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/MATLAB_Tools/find_components
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/MATLAB_Tools/GEE
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/MATLAB_Tools/shellgui
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/MATLAB_Tools/waitmex
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/MATLAB_Tools/spqr_rank
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/MATLAB_Tools/spqr_rank/SJget
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/MATLAB_Tools/SuiteSparseCollection
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/MATLAB_Tools/SSMULT
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/MATLAB_Tools/dimacs10
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/MATLAB_Tools/spok
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/MATLAB_Tools/sparseinv
addpath /home/lxue07/Documents/SuiteSparse-5.4.0/SuiteSparse/Mongoose/MATLAB